import type { ReactNode } from 'react'
import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type LanguageCode = 'english' | 'kannada' | 'hindi' | 'tamil' | 'telugu' | 'malayalam' | 'marathi'

type LanguageContextValue = {
  language: LanguageCode
  setLanguage: (language: LanguageCode) => void
  t: (key: string, fallback?: string) => string
}

const STORAGE_KEY = 'rrdch-language'

const translations: Record<LanguageCode, Record<string, string>> = {
  english: {
    'header.utility': 'RajaRajeswari Dental College & Hospital, Bengaluru',
    'header.city': 'Bangalore, Karnataka',
    'header.title': 'RajaRajeswari Dental College & Hospital',
    'header.subtitle': 'Recognised by Royal College of Physicians and Surgeons of Glasgow, UK for part 1 & 2 MFDS Examinations',
    'contacts.title': 'Contacts',
    'contacts.phone': 'Phone',
    'contacts.telefax': 'Tele-Fax',
    'contacts.mobile': 'Mobile',
    'contacts.email': 'Email',
    'actions.bookAppointment': 'Book Appointment',
    'actions.emergency': 'Emergency',
    'actions.studentErp': 'Student ERP',
    'search.label': 'Search',
    'search.placeholder': 'Search pages',
    'search.go': 'Go',
    'search.empty': 'No matching pages found.',
    'nav.home': 'Home',
    'nav.aboutUs': 'About Us',
    'nav.trust': 'Trust',
    'nav.management': 'Management',
    'nav.governingCouncil': 'Governing Council',
    'nav.visionMission': 'Vision & Mission',
    'nav.coursesOffered': 'Courses Offered',
    'nav.bds': 'Bachelor of Dental Surgery (BDS)',
    'nav.mds': 'Master of Dental Surgery (MDS)',
    'nav.phd': 'Ph.D',
    'nav.certificateCourse': 'Certificate Course',
    'nav.academics': 'Academics',
    'nav.admissionEnquiry': 'Admission Enquiry',
    'nav.achievements': 'Achievements',
    'nav.extraCurricular': 'Extra Curricular Activities',
    'nav.feedback': 'Feedback',
    'nav.calendar': 'Calendar of Events',
    'nav.timeTable': 'Time Table',
    'nav.facilities': 'Facilities',
    'nav.auditorium': 'Auditorium',
    'nav.cafeteria': 'Cafeteria',
    'nav.classroom': 'Classroom',
    'nav.digitalLibrary': 'Digital Library',
    'nav.gymnasium': 'Gymnasium',
    'nav.hostel': 'Hostel',
    'nav.sportsRecreation': 'Sports & Recreation',
    'nav.transportation': 'Transportation',
    'nav.gallery': 'Gallery',
    'nav.photoGallery': 'Photo Gallery',
    'nav.videoGallery': 'Video Gallery',
    'nav.newsEvents': 'News & Events',
    'nav.alumni': 'Alumni',
    'nav.contactUs': 'Contact Us',
    'home.highlightsEyebrow': 'Admissions & Highlights',
    'home.highlightsTitle': 'Admissions, highlights and programme information.',
    'home.announcement.implantology': 'Application are invited from eligible candidates for Certificate Course in Implantology 2026-27, Interested candidates send your application to: pgrrdc@gmail.com',
    'home.announcement.phd': 'Ph.D Entrance Exam Notification',
    'home.announcement.admission': 'Admission Enquiry for 2026-27',
    'home.fact.established': 'Established',
    'home.fact.bdsAdmissions': 'BDS admissions',
    'home.fact.modernUnits': 'Modern dental units / chairs',
    'home.fact.patients': 'Patients treated daily',
    'home.programme.certificate': 'Certificate',
    'home.snapshotEyebrow': 'Institution Snapshot',
    'home.snapshotTitle': "Chairman's Desk, College and Hospital.",
    'home.spotlight.chairman': "Chairman's Desk",
    'home.spotlight.college': 'College',
    'home.spotlight.hospital': 'Hospital',
    'home.readMore': 'Read More',
    'home.tourEyebrow': 'Campus Tour',
    'home.tourTitle': 'Explore the RRDCH campus virtual tour.',
    'footer.groupEyebrow': 'RajaRajeswari Group of Institutions',
    'footer.groupTitle': 'Connected campuses and partner institutions.',
    'footer.accreditationTitle': 'Accreditations & Recognitions',
    'footer.tagline': 'RajaRajeswari Dental College & Hospital',
    'footer.explore': 'Explore',
    'footer.courses': 'Courses',
    'footer.connect': 'Connect',
    'footer.socialCopy': 'Official social links.',
    'footer.rights': '2013 RRDCH. All Rights Reserved.',
    'footer.hosted': 'Site Hosted, Designed and Maintained by RRDCH'
  },
  kannada: {
    'header.utility': 'ರಾಜರಾಜೇಶ್ವರಿ ಡೆಂಟಲ್ ಕಾಲೇಜ್ ಮತ್ತು ಆಸ್ಪತ್ರೆ, ಬೆಂಗಳೂರು',
    'header.city': 'ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ',
    'contacts.title': 'ಸಂಪರ್ಕಗಳು',
    'contacts.phone': 'ದೂರವಾಣಿ',
    'contacts.telefax': 'ಟೆಲಿ-ಫ್ಯಾಕ್ಸ್',
    'contacts.mobile': 'ಮೊಬೈಲ್',
    'contacts.email': 'ಇಮೇಲ್',
    'actions.bookAppointment': 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್',
    'actions.emergency': 'ತುರ್ತು',
    'actions.studentErp': 'ವಿದ್ಯಾರ್ಥಿ ERP',
    'search.label': 'ಹುಡುಕಿ',
    'search.placeholder': 'ಪುಟಗಳನ್ನು ಹುಡುಕಿ',
    'search.go': 'ಹೋಗಿ',
    'search.empty': 'ಹೊಂದುವ ಪುಟಗಳು ಸಿಗಲಿಲ್ಲ.',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.aboutUs': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'nav.coursesOffered': 'ಕೋರ್ಸ್‌ಗಳು',
    'nav.academics': 'ಅಕಾಡೆಮಿಕ್ಸ್',
    'nav.facilities': 'ಸೌಲಭ್ಯಗಳು',
    'nav.gallery': 'ಗ್ಯಾಲರಿ',
    'nav.newsEvents': 'ಸುದ್ದಿ ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು',
    'nav.alumni': 'ಹಳೆ ವಿದ್ಯಾರ್ಥಿಗಳು',
    'nav.contactUs': 'ಸಂಪರ್ಕಿಸಿ',
    'home.highlightsEyebrow': 'ಪ್ರವೇಶಗಳು ಮತ್ತು ಮುಖ್ಯಾಂಶಗಳು',
    'home.highlightsTitle': 'ಪ್ರವೇಶಗಳು, ಮುಖ್ಯಾಂಶಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ರಮ ಮಾಹಿತಿ.',
    'home.announcement.phd': 'ಪಿ.ಎಚ್.ಡಿ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಸೂಚನೆ',
    'home.announcement.admission': '2026-27 ಪ್ರವೇಶ ವಿಚಾರಣೆ',
    'home.fact.established': 'ಸ್ಥಾಪನೆ',
    'home.fact.bdsAdmissions': 'BDS ಪ್ರವೇಶಗಳು',
    'home.fact.modernUnits': 'ಆಧುನಿಕ ಡೆಂಟಲ್ ಯುನಿಟ್‌ಗಳು / ಕುರ್ಚಿಗಳು',
    'home.fact.patients': 'ದಿನಸಿ ಚಿಕಿತ್ಸೆಯ ರೋಗಿಗಳು',
    'home.snapshotEyebrow': 'ಸಂಸ್ಥೆಯ ಚಿತ್ರಣ',
    'home.snapshotTitle': 'ಚೇರ್ಮನ್ ಡೆಸ್ಕ್, ಕಾಲೇಜು ಮತ್ತು ಆಸ್ಪತ್ರೆ.',
    'home.readMore': 'ಇನ್ನಷ್ಟು ಓದಿ',
    'home.tourEyebrow': 'ಕ್ಯಾಂಪಸ್ ಟೂರ್',
    'home.tourTitle': 'RRDCH ಕ್ಯಾಂಪಸ್ ವರ್ಚುವಲ್ ಟೂರ್ ನೋಡಿ.',
    'footer.groupEyebrow': 'ರಾಜರಾಜೇಶ್ವರಿ ಗುಂಪಿನ ಸಂಸ್ಥೆಗಳು',
    'footer.groupTitle': 'ಸಂಬಂಧಿತ ಕ್ಯಾಂಪಸ್‌ಗಳು ಮತ್ತು ಪಾಲುದಾರ ಸಂಸ್ಥೆಗಳು.',
    'footer.accreditationTitle': 'ಮಾನ್ಯತೆಗಳು ಮತ್ತು ಗುರುತింపುಗಳು',
    'footer.explore': 'ಅನ್ವೇಷಿಸಿ',
    'footer.courses': 'ಕೋರ್ಸ್‌ಗಳು',
    'footer.connect': 'ಸಂಪರ್ಕಿಸಿ',
    'footer.socialCopy': 'ಅಧಿಕೃತ ಸಾಮಾಜಿಕ ಲಿಂಕ್‌ಗಳು.',
    'footer.rights': '2013 RRDCH. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    'footer.hosted': 'ಸೈಟ್ ಅನ್ನು RRDCH ವಿನ್ಯಾಸಗೊಳಿಸಿ ನಿರ್ವಹಿಸಿದೆ'
  },
  hindi: {
    'header.utility': 'राजराजेश्वरी डेंटल कॉलेज और अस्पताल, बेंगलुरु',
    'header.city': 'बेंगलुरु, कर्नाटक',
    'contacts.title': 'संपर्क',
    'contacts.phone': 'फ़ोन',
    'contacts.telefax': 'टेली-फैक्स',
    'contacts.mobile': 'मोबाइल',
    'contacts.email': 'ईमेल',
    'actions.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'actions.emergency': 'आपातकाल',
    'actions.studentErp': 'स्टूडेंट ERP',
    'search.label': 'खोज',
    'search.placeholder': 'पेज खोजें',
    'search.go': 'जाएं',
    'search.empty': 'कोई मेल खाते पेज नहीं मिले।',
    'nav.home': 'होम',
    'nav.aboutUs': 'हमारे बारे में',
    'nav.coursesOffered': 'पाठ्यक्रम',
    'nav.academics': 'अकादमिक',
    'nav.facilities': 'सुविधाएँ',
    'nav.gallery': 'गैलरी',
    'nav.newsEvents': 'समाचार और कार्यक्रम',
    'nav.alumni': 'पूर्व छात्र',
    'nav.contactUs': 'संपर्क करें',
    'home.highlightsEyebrow': 'प्रवेश और मुख्य बिंदु',
    'home.highlightsTitle': 'प्रवेश, मुख्य बिंदु और कार्यक्रम जानकारी।',
    'home.announcement.phd': 'पीएचडी प्रवेश परीक्षा सूचना',
    'home.announcement.admission': '2026-27 प्रवेश पूछताछ',
    'home.fact.established': 'स्थापित',
    'home.fact.bdsAdmissions': 'BDS प्रवेश',
    'home.fact.modernUnits': 'आधुनिक डेंटल यूनिट / चेयर',
    'home.fact.patients': 'प्रतिदिन उपचारित मरीज',
    'home.snapshotEyebrow': 'संस्थान झलक',
    'home.snapshotTitle': 'चेयरमैन डेस्क, कॉलेज और अस्पताल।',
    'home.readMore': 'और पढ़ें',
    'home.tourEyebrow': 'कैंपस टूर',
    'home.tourTitle': 'RRDCH कैंपस का वर्चुअल टूर देखें।',
    'footer.groupEyebrow': 'राजराजेश्वरी समूह संस्थान',
    'footer.groupTitle': 'जुड़े हुए कैंपस और साझेदार संस्थान।',
    'footer.accreditationTitle': 'मान्यताएँ और पहचान',
    'footer.explore': 'एक्सप्लोर',
    'footer.courses': 'पाठ्यक्रम',
    'footer.connect': 'जुड़ें',
    'footer.socialCopy': 'आधिकारिक सोशल लिंक।',
    'footer.rights': '2013 RRDCH. सर्वाधिकार सुरक्षित।',
    'footer.hosted': 'साइट RRDCH द्वारा होस्ट, डिज़ाइन और मेंटेन की गई है'
  },
  tamil: {
    'header.utility': 'ராஜராஜேஸ்வரி டென்டல் கல்லூரி மற்றும் மருத்துவமனை, பெங்களூரு',
    'header.city': 'பெங்களூரு, கர்நாடகா',
    'contacts.title': 'தொடர்புகள்',
    'contacts.phone': 'தொலைபேசி',
    'contacts.telefax': 'டெலி-ஃபாக்ஸ்',
    'contacts.mobile': 'மொபைல்',
    'contacts.email': 'மின்னஞ்சல்',
    'actions.bookAppointment': 'நியமனம் பதிவு',
    'actions.emergency': 'அவசரம்',
    'actions.studentErp': 'மாணவர் ERP',
    'search.label': 'தேடல்',
    'search.placeholder': 'பக்கங்களை தேடவும்',
    'search.go': 'செல்',
    'search.empty': 'பொருந்தும் பக்கங்கள் கிடைக்கவில்லை.',
    'nav.home': 'முகப்பு',
    'nav.aboutUs': 'எங்களை பற்றி',
    'nav.coursesOffered': 'பாடத்திட்டங்கள்',
    'nav.academics': 'கல்வி',
    'nav.facilities': 'வசதிகள்',
    'nav.gallery': 'காட்சியகம்',
    'nav.newsEvents': 'செய்தி & நிகழ்வுகள்',
    'nav.alumni': 'முன்னாள் மாணவர்கள்',
    'nav.contactUs': 'தொடர்பு கொள்ள',
    'home.highlightsEyebrow': 'சேர்க்கை & முக்கிய அம்சங்கள்',
    'home.highlightsTitle': 'சேர்க்கைகள், முக்கிய அம்சங்கள் மற்றும் திட்ட தகவல்.',
    'home.readMore': 'மேலும் படிக்க',
    'footer.explore': 'ஆராயுங்கள்',
    'footer.courses': 'பாடங்கள்',
    'footer.connect': 'இணைக்க',
    'footer.socialCopy': 'அதிகாரப்பூர்வ சமூக இணைப்புகள்.'
  },
  telugu: {
    'header.utility': 'రాజరాజేశ్వరి డెంటల్ కాలేజ్ అండ్ హాస్పిటల్, బెంగళూరు',
    'header.city': 'బెంగళూరు, కర్ణాటక',
    'contacts.title': 'సంప్రదింపులు',
    'contacts.phone': 'ఫోన్',
    'contacts.telefax': 'టెలి-ఫ్యాక్స్',
    'contacts.mobile': 'మొబైల్',
    'contacts.email': 'ఈమెయిల్',
    'actions.bookAppointment': 'అపాయింట్‌మెంట్ బుక్',
    'actions.emergency': 'అత్యవసరం',
    'actions.studentErp': 'స్టూడెంట్ ERP',
    'search.label': 'శోధన',
    'search.placeholder': 'పేజీలు శోధించండి',
    'search.go': 'వెళ్ళు',
    'search.empty': 'సరిపడే పేజీలు లేవు.',
    'nav.home': 'హోమ్',
    'nav.aboutUs': 'మా గురించి',
    'nav.coursesOffered': 'కోర్సులు',
    'nav.academics': 'అకాడెమిక్స్',
    'nav.facilities': 'సౌకర్యాలు',
    'nav.gallery': 'గ్యాలరీ',
    'nav.newsEvents': 'వార్తలు & కార్యక్రమాలు',
    'nav.alumni': 'పూర్వ విద్యార్థులు',
    'nav.contactUs': 'సంప్రదించండి',
    'home.highlightsEyebrow': 'అడ్మిషన్లు & ముఖ్యాంశాలు',
    'home.highlightsTitle': 'అడ్మిషన్లు, ముఖ్యాంశాలు మరియు కార్యక్రమ సమాచారం.',
    'home.readMore': 'మరింత చదవండి',
    'footer.explore': 'అన్వేషించండి',
    'footer.courses': 'కోర్సులు',
    'footer.connect': 'కనెక్ట్',
    'footer.socialCopy': 'అధికారిక సోషల్ లింకులు.'
  },
  malayalam: {
    'header.utility': 'രാജരാജേശ്വരി ഡെന്റൽ കോളേജ് ആൻഡ് ഹോസ്പിറ്റൽ, ബെംഗളൂരു',
    'header.city': 'ബെംഗളൂരു, കര്‍ണാടക',
    'contacts.title': 'ബന്ധപ്പെടുക',
    'contacts.phone': 'ഫോൺ',
    'contacts.telefax': 'ടെലി-ഫാക്സ്',
    'contacts.mobile': 'മൊബൈൽ',
    'contacts.email': 'ഇമെയിൽ',
    'actions.bookAppointment': 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    'actions.emergency': 'അടിയന്തിരം',
    'actions.studentErp': 'സ്റ്റുഡന്റ് ERP',
    'search.label': 'തിരയുക',
    'search.placeholder': 'പേജുകൾ തിരയുക',
    'search.go': 'പോകുക',
    'search.empty': 'ഒത്ത പേജുകൾ ലഭിച്ചില്ല.',
    'nav.home': 'ഹോം',
    'nav.aboutUs': 'ഞങ്ങളേക്കുറിച്ച്',
    'nav.coursesOffered': 'കോഴ്സുകൾ',
    'nav.academics': 'അക്കാദമിക്സ്',
    'nav.facilities': 'സൗകര്യങ്ങൾ',
    'nav.gallery': 'ഗാലറി',
    'nav.newsEvents': 'വാർത്തകളും ഇവന്റുകളും',
    'nav.alumni': 'അലുമ്നി',
    'nav.contactUs': 'ബന്ധപ്പെടുക',
    'home.highlightsEyebrow': 'അഡ്മിഷനും ഹൈലൈറ്റുകളും',
    'home.highlightsTitle': 'അഡ്മിഷൻ, ഹൈലൈറ്റുകൾ, പ്രോഗ്രാം വിവരങ്ങൾ.',
    'home.readMore': 'കൂടുതൽ വായിക്കുക',
    'footer.explore': 'പരിശോധിക്കുക',
    'footer.courses': 'കോഴ്സുകൾ',
    'footer.connect': 'ബന്ധപ്പെടുക',
    'footer.socialCopy': 'ഓഫീഷ്യൽ സോഷ്യൽ ലിങ്കുകൾ.'
  },
  marathi: {
    'header.utility': 'राजराजेश्वरी डेंटल कॉलेज आणि हॉस्पिटल, बेंगळुरू',
    'header.city': 'बेंगळुरू, कर्नाटक',
    'contacts.title': 'संपर्क',
    'contacts.phone': 'फोन',
    'contacts.telefax': 'टेली-फॅक्स',
    'contacts.mobile': 'मोबाईल',
    'contacts.email': 'ईमेल',
    'actions.bookAppointment': 'अपॉइंटमेंट बुक करा',
    'actions.emergency': 'आपत्कालीन',
    'actions.studentErp': 'स्टुडंट ERP',
    'search.label': 'शोधा',
    'search.placeholder': 'पाने शोधा',
    'search.go': 'जा',
    'search.empty': 'जुळणारी पाने सापडली नाहीत.',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.aboutUs': 'आमच्याबद्दल',
    'nav.coursesOffered': 'अभ्यासक्रम',
    'nav.academics': 'अकॅडेमिक्स',
    'nav.facilities': 'सुविधा',
    'nav.gallery': 'गॅलरी',
    'nav.newsEvents': 'बातम्या व कार्यक्रम',
    'nav.alumni': 'माजी विद्यार्थी',
    'nav.contactUs': 'संपर्क करा',
    'home.highlightsEyebrow': 'प्रवेश व ठळक मुद्दे',
    'home.highlightsTitle': 'प्रवेश, ठळक मुद्दे आणि कार्यक्रम माहिती.',
    'home.readMore': 'अधिक वाचा',
    'footer.explore': 'एक्सप्लोर',
    'footer.courses': 'अभ्यासक्रम',
    'footer.connect': 'जोडा',
    'footer.socialCopy': 'अधिकृत सोशल लिंक.'
  }
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageCode>('english')

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem(STORAGE_KEY) as LanguageCode | null

    if (savedLanguage && savedLanguage in translations) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage)
    window.localStorage.setItem(STORAGE_KEY, nextLanguage)
  }

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key: string, fallback?: string) => translations[language][key] ?? translations.english[key] ?? fallback ?? key
    }),
    [language]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }

  return context
}
